#!/usr/bin/env node
/* device-ledger.mjs — D11/P5: workstation capability inventory.

   Two artifacts, split by classification:
     security/out/device-ledger.json   — local ledger: full capability
       detail (versions, flag classes, model counts). Disk-local like the
       rest of security/out — evidence, not published.
     site/assets/device-ledger.json    — sanitized public projection:
       booleans and counts ONLY. No paths, hostnames, addresses, serials,
       or officer material — same sanitation convention as the census
       and archive projections.

   What it measures (mechanically, no claims):
     cpu      — core count + SIMD flag classes from /proc/cpuinfo
     mem      — total GB (rounded) from /proc/meminfo
     runtimes — zig/node/python/dotnet/go/cargo: presence + version class
     gpu      — DRM render nodes + vulkaninfo reachability + vendor class
     ollama   — governed runtime liveness + resident model count
     registry — sibling capability-registry hash (drift detector)

   Modes:  (bare) dry-run · --emit write both · --verify ratchet
   Ratchet: a capability that was present can't silently vanish —
   absences are findings, additions are growth (allowed).
*/
import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import crypto from "node:crypto";
import { execSync } from "node:child_process";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const OUT = path.join(ROOT, "security", "out");
const SITE = path.join(ROOT, "site", "assets", "device-ledger.json");
const EMIT = process.argv.includes("--emit");
const VERIFY = process.argv.includes("--verify");

const sh = (cmd) => { try { return execSync(cmd, { encoding: "utf8", timeout: 5000, stdio: ["pipe","pipe","ignore"] }).trim(); } catch { return null; } };

/* ---------- cpu ---------- */
const cpuinfo = fs.existsSync("/proc/cpuinfo")
  ? fs.readFileSync("/proc/cpuinfo", "utf8") : "";
const flags = (cpuinfo.match(/^flags\s*:\s*(.+)$/m)?.[1] || "").split(/\s+/);
const SIMD = ["avx512f", "avx512bw", "avx2", "avx", "sse4_2", "ssse3", "sse3", "neon", "asimd"];
const cpu = {
  cores: (cpuinfo.match(/^processor/gm) || []).length,
  simd: SIMD.filter(f => flags.includes(f)),
  arch: sh("uname -m") || "unknown",
};

/* ---------- memory ---------- */
const meminfo = fs.existsSync("/proc/meminfo")
  ? fs.readFileSync("/proc/meminfo", "utf8") : "";
const memKb = parseInt(meminfo.match(/^MemTotal:\s*(\d+)/m)?.[1] || "0", 10);
const mem = { total_gb: Math.round(memKb / 1024 / 1024) };

/* ---------- runtimes (presence + version class only) ---------- */
const RT = {
  zig: ["zig", "version"], node: ["node", "--version"],
  python: ["python3", "--version"], dotnet: ["dotnet", "--version"],
  go: ["go", "version"], cargo: ["cargo", "--version"],
  lean: ["lake", "--version"], deno: ["deno", "--version"],
  wasmtime: ["wasmtime", "--version"],
};
const runtimes = {};
for (const [name, [bin, flag]] of Object.entries(RT)) {
  const v = sh(`${bin} ${flag}`);
  runtimes[name] = v === null ? "absent" : v.split(/\s+/).pop().replace(/^v/, "");
}

/* ---------- gpu ---------- */
const drm = fs.existsSync("/dev/dri")
  ? fs.readdirSync("/dev/dri").filter(f => f.startsWith("renderD")).length : 0;
const lspci = sh("lspci") || "";
const vgaLine = (lspci.match(/VGA.*|3D controller.*/i)?.[0] || "");
const vendor = /amd|advanced micro/i.test(vgaLine) ? "amd"
  : /nvidia/i.test(vgaLine) ? "nvidia"
  : /intel/i.test(vgaLine) ? "intel" : "other";
const gpu = {
  present: drm > 0 || vgaLine.length > 0,
  render_nodes: drm,
  vendor_class: vendor,
  vulkan_reachable: sh("vulkaninfo --summary") !== null,
};

/* ---------- ollama (governed runtime) ---------- */
const ollamaProbe = () => new Promise((resolve) => {
  const req = http.get({ host: "127.0.0.1", port: 11434, path: "/api/tags", timeout: 1500 },
    (res) => {
      let body = "";
      res.on("data", d => body += d);
      res.on("end", () => {
        try {
          const j = JSON.parse(body);
          resolve({ resident: true, models: (j.models || []).length });
        } catch { resolve({ resident: true, models: -1 }); }
      });
    });
  req.on("timeout", () => { req.destroy(); resolve({ resident: false, models: 0 }); });
  req.on("error", () => resolve({ resident: false, models: 0 }));
});
const ollama = await ollamaProbe();

/* ---------- sibling registry hash ---------- */
const regPath = path.join(ROOT, "site", "assets", "capability-registry.json");
const registry = fs.existsSync(regPath)
  ? crypto.createHash("sha256").update(fs.readFileSync(regPath)).digest("hex").slice(0, 16)
  : null;

/* ---------- report ---------- */
const ledger = {
  spec: "DEVICELEDGERv1",
  generated: new Date().toISOString(),
  note: "workstation capability inventory — generated by tools/device-ledger.mjs; public projection carries booleans/counts only",
  cpu, mem, runtimes, gpu, ollama, registry,
};

/* sanitized projection — strip versions to classes, keep booleans+counts */
const projection = {
  spec: ledger.spec,
  generated: ledger.generated,
  cpu: { cores: cpu.cores, arch: cpu.arch, simd: cpu.simd },
  mem_gb: mem.total_gb,
  runtimes: Object.fromEntries(Object.entries(runtimes)
    .map(([k, v]) => [k, v !== "absent"])),
  gpu: { present: gpu.present, render_nodes: gpu.render_nodes,
         vendor_class: gpu.vendor_class, vulkan: gpu.vulkan_reachable },
  ollama: { resident: ollama.resident, models: ollama.models },
};

/* ---------- verify: capability ratchet ---------- */
if (VERIFY) {
  const prev = JSON.parse(fs.readFileSync(SITE, "utf8"));
  const lost = [];
  for (const [k, wasPresent] of Object.entries(prev.runtimes || {})) {
    if (wasPresent && !projection.runtimes[k]) lost.push(`runtime:${k}`);
  }
  if (prev.cpu?.cores > projection.cpu.cores) lost.push("cpu:cores");
  if (prev.gpu?.present && !projection.gpu.present) lost.push("gpu");
  for (const f of prev.cpu?.simd || []) {
    if (!projection.cpu.simd.includes(f)) lost.push(`simd:${f}`);
  }
  console.log(lost.length === 0
    ? `device verify: GREEN — ${cpu.cores} cores, ${cpu.simd.length} SIMD classes, ${Object.values(runtimes).filter(v => v !== "absent").length}/${Object.keys(runtimes).length} runtimes`
    : `device verify: LOST — capabilities vanished: ${lost.join(", ")}`);
  process.exit(lost.length === 0 ? 0 : 1);
}
if (EMIT) {
  fs.mkdirSync(OUT, { recursive: true });
  fs.mkdirSync(path.dirname(SITE), { recursive: true });
  fs.writeFileSync(path.join(OUT, "device-ledger.json"), JSON.stringify(ledger, null, 2) + "\n");
  fs.writeFileSync(SITE, JSON.stringify(projection, null, 2) + "\n");
  console.log(`device ledger → security/out/device-ledger.json + site/assets/device-ledger.json ` +
    `(${cpu.cores} cores/${cpu.arch}, ${mem.total_gb}GB, gpu:${gpu.vendor_class}, ollama:${ollama.resident ? ollama.models + " models" : "absent"})`);
} else {
  console.log(JSON.stringify(projection, null, 2));
  console.log(`DRY — ${Object.values(runtimes).filter(v => v !== "absent").length}/${Object.keys(runtimes).length} runtimes present; --emit to write`);
}
