#!/usr/bin/env node
// slate-ledger.mjs — emit site/assets/production-ledger.json: the canon
// asset inventory the Director's Room storyboards over. Every entry is
// extracted from a real source file — nothing is authored by hand here,
// so a claim, a codex entry, or a family member can't silently vanish
// from the slate while still being canon.
//
//   node tools/slate-ledger.mjs           # dry-run
//   node tools/slate-ledger.mjs --emit    # write the ledger
import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const SITE = path.join(ROOT, "site");
const OUT = path.join(SITE, "assets", "production-ledger.json");
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");

const entries = [];

/* dossier claims — ids straight out of the published table
   (two canon formats: early rows are <td>C01</td>, late rows are | C56 |) */
const dossier = read("site/dossier.html");
const claimIds = [...new Set([
  ...dossier.matchAll(/\| (C\d{2,3}) \|/g),
  ...dossier.matchAll(/<td>(C\d{2,3})<\/td>/g),
].map(m => m[1]))].sort();
for (const c of claimIds) entries.push({ id: c, kind: "claim", title: "dossier claim " + c });

/* anomaly codex — keys of the lore map */
const desk = read("site/assets/fano-desktop.js");
const lore = desk.match(/var ANOMALY_LORE = \{([\s\S]*?)\n  \};/);
const loreKeys = lore
  ? [...lore[1].matchAll(/^\s*"([^"]+)":/gm)].map(m => m[1]).sort() : [];
for (const k of loreKeys)
  entries.push({ id: "lore:" + k, kind: "codex", title: k });

/* top-level dossier pages — the en surfaces (zh twins ride along) */
const pages = fs.readdirSync(SITE).filter(f => f.endsWith(".html") &&
  !f.endsWith("-zh.html")).sort();
for (const p of pages)
  entries.push({ id: "page:" + p, kind: "page", title: p });

/* family shelf — the sibling roster, doc-cited */
const qup = read("site/assets/quplink.js");
const fam = [...qup.matchAll(/name: "([^"]+)"/g)].map(m => m[1]);
for (const [i, n] of [...new Set(fam)].entries())
  entries.push({ id: "family:" + i, kind: "family", title: n });

/* the viz deck — every render pane is a shot type */
const viz = read("site/assets/quplink-viz.js");
const vizIds = [...viz.matchAll(/^\s*\["([a-z0-9]+)",/gm)].map(m => m[1]);
for (const v of vizIds)
  entries.push({ id: "viz:" + v, kind: "viz", title: "render: " + v });

const ledger = {
  spec: "PRODUCERv1",
  generated: new Date().toISOString(),
  note: "canon asset inventory — generated by tools/slate-ledger.mjs; the Director's Room boards shots over this, read-only over canon",
  asset_count: entries.length,
  by_kind: entries.reduce((a, e) => (a[e.kind] = (a[e.kind] || 0) + 1, a), {}),
  assets: entries,
};

if (!process.argv.includes("--emit")) {
  console.log(JSON.stringify({ ...ledger, assets: `[${entries.length} entries]` }, null, 2));
  console.error("dry-run — --emit to write site/assets/production-ledger.json");
  process.exit(0);
}
fs.writeFileSync(OUT, JSON.stringify(ledger, null, 2));
console.log(`production ledger → ${OUT} (${entries.length} assets: ${JSON.stringify(ledger.by_kind)})`);
